lasso-js/lasso

README.md
lib/dependencies/Dependency.js
test/optimizer-test.js
test/test-project-globs/relative-paths.optimizer.json

This is proposed fix for https://github.com/raptorjs/optimizer/issues/39

Modify Dependency resolvePath to try require.resolve(...) convention first when path does not start with "." or "/"

---

lib/dependencies/dependency-resource.js
test/fixtures/mask-define/library.js
test/lasso-test.js

Added the `mask-define` option. This can be useful to skip the `define` check when including libraries with a UMD-style wrapper. Let me know of any changes needed.

add mask-define option for resource dependencies

---

lib/config-loader.js
test/.jshintrc
test/config-test.js

Fix: don't copy `options` into `configDefaults`. Instead, copy `configDefaults` into `options` (don't override any properties that `options` already has).

Fixes #91 - Lasso config defaults get polluted each time Lasso is configured

---

CHANGELOG.md
README.md
lib/Config.js
lib/Lasso.js
lib/LassoPageResult.js
lib/config-loader.js

This change allows a build tool to create and capture fingerprints for all inline code blocks for the purpose of generating a Content Security Policy. This change is especially useful for building single page apps which are statically built once and cannot leverage a _nonce_.
The solution in this pull request will also work when the lasso page result is serialized to cache and deserialized from cache.

Fixes #108 - Add support for fingerprinting inline code blocks for building SPA with CSP

---

lib/dependencies/DependencyRegistry.js

This caused an issue with my plugin when I did not define the optional `getLastModified` but the app crashed and the stack trace said it could not find said method. Looking at the source it appears these blocks should be flipped.

registerRequireType, switch condition blocks

---

lib/Lasso.js
test/lasso-test.js

It looks like since the addition of custom resource attributes from #107, external url strings will always get parsed through Marko and get escaped. Therefore, I've removed `escapeXmlAttr` in those cases so that they don't get double escaped. Let me know if you'd like to fix this in some other way (escape it explicitly and disable escaping through Marko?)

Fixes #117 - external dependency url improperly encoded

---

package.json

Teams have a direct dependency on `lasso` and this will help update to the latest version of `lasso-require`. Can you please merge this and publish a new 1.x `lasso` module.

Updating the latest 1.x version of lasso-require

---

package.json

When using lasso-babel-transform, I received the following error:
```javascript
node_modules/lasso-tools/node_modules/lasso/node_modules/lasso-require/src/util/Transforms.js:49
return input.pipe(transformFunc(path));
^
TypeError: transformFunc is not a function
at applyTransform (node_modules/lasso-tools/node_modules/lasso/node_modules/lasso-require/src/util/Transforms.js:49:27)
at DeferredReadable.<anonymous> (node_modules/lasso-tools/node_modules/lasso/node_modules/lasso-require/src/util/Transforms.js:73:19)
at DeferredReadable._read (node_modules/lasso-tools/node_modules/lasso/lib/util/DeferredReadable.js:73:38)
at DeferredReadable.Readable.read (_stream_readable.js:336:10)
at resume_ (_stream_readable.js:726:12)
at nextTickCallbackWith2Args (node.js:442:9)
at …
```

Upgrade lasso-require to fix transforms

---

middleware/koa/serveStatic.js
middleware/serveStatic.js
package.json

Fixed a tmp solution for working with Koajs.

Fixed for Koajs

---

package.json

Updates `package.json` to use the latest version of `glob`. This should stop those npm errors:
```
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```
The primary usage of the module hasn't changed much, and the single use of it in the repo looks like it's fine (and the glob tests still pass).

upgrade glob dependency

---

README.md
lib/Bundle.js
lib/Lasso.js
lib/dependencies/Dependency.js
package.json
test/autotests/bundling/external-js-integrity/package.json
test/autotests/bundling/external-js-integrity/test.js

Adding an `attributes` object to a dependency definition will result in those attributes being defined on the html tag for that dependency.  For bundled dependencies, these attributes will be merged with latter dependencies taking priority.
The following is an example using the `integrity` and `crossorigin` attributes for [Subresource Integrity (SRI) checking](https://www.w3.org/TR/SRI/). This allows browsers to ensure that resources hosted on third-party servers have not been tampered with. Use of SRI is recommended as a best-practice, whenever libraries are loaded from a third-party source.
``` json
{
"dependencies": [
{
"type": "js",
"url": "https://code.jquery.com/jquery-3.1.1.min.js",
"attributes":{
"integrity":"sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=", …
```

Bundle attributes

---

CHANGELOG.md
lib/dependencies/dependency-intersection.js
test/autotests/bundling/intersection-threshold-2-require/a.js
test/autotests/bundling/intersection-threshold-2-require/b.js
test/autotests/bundling/intersection-threshold-2-require/main.browser.json
test/autotests/bundling/intersection-threshold-2-require/package.json
test/autotests/bundling/intersection-threshold-2-require/shared.js
test/autotests/bundling/intersection-threshold-2-require/test.js

Defining bundles with "intersection" does not work for "require" dependencies.
`dependency-require` uses data in `lasso-context.phaseData['dependency-require']` to avoid walking the same dependency multiple times. It seems like a hack, but I simply reset the `lassoContext.phaseData` object before walking the dependencies and then I restore the old phase data when done.
See https://github.com/lasso-js/lasso-require/blob/master/src/util/Deduper.js#L20

Fixes #180 - Defining bundles with "intersection" does not work for "require" dependencies

---

lib/LassoPageResult.js
package.json

This was throwing warnings in parent projects. I only updated this one instance, and did not go through the whole repo and update similar potential changes in tests.
Theoretically this now needs a recent marko version, so I updated that in the package.json, but that would also probably make this more than a semver patch.

use renderToString instead of renderSync

---

taglib/config-tag.js

The switch from `page-tag` to `config-tag` in [this PR](https://github.com/lasso-js/lasso/commit/0657b12b3b02395b4f16ea3f5cd59931fcb571b0) is breaking our builds, since `slot-tag.js` reads the timeout parameter from `lassoRenderContext.data.timeout`.

Fix for broken timeout parameter

---

README.md

Adding new lasso plugin to the third-party plugins list to support RTL css by transforming CSS from left-to-right to right-to-left using [rtlcss](https://www.npmjs.com/package/rtlcss).

Adding lasso-rtl-css as third-party plugin

---

README.md

Noticed that the link to `serveStatic` doesn't go anywhere and it probably doesn't make sense to anyway.

Remove unset link in readme.

---

package.json

This fixes #225.
NOTE: We have a bit of a dependency problem because `marko-starter` and `marko-magic` pull in different versions of `lasso`.  We need to upgrade `lasso` in `marko-starter` and make `lasso` a peer dependency in `marko-magic`.
I have a PR to fix `marko-magic`. See https://github.com/mlrawlings/marko-magic/pull/1

Upgrade esprima - Fixes #225

---

README.md

There were a few leftover references to `$rmod`, which was used with `raptor` naming in earlier versions.

update $rmod references to $_mod

---

package.json
src/Lasso.js
src/Slot.js

This fixes console warnings when using lasso with the latest version of Marko where the old attribute spread syntax has been deprecated.

Upgrade marko templates to use spread attribute syntax

---

env.js
package.json

Node.js >=v10 was recognized as >= v8.0, triggering the compat mode.
The right thing to do seems to use the semver module.
Tests pass locally fine except:
* lasso-lassoResource-buffer: `expected '/static/cf6691ad.png' to equal '/static/02827b0c.png'`
* lasso-lassoResource-buffer-name: `expected '/static/test-cf6691ad.png' to equal '/static/test-02827b0c.png'`
I use the nodejs-10.1.0-1 package on Arch Linux.
`tag/v3.1.5` fails in the same way. 
Maybe a random number generator seed change ?

Support Node.js >= v10 with proper SemVer check

---

src/Lasso.js

Two events are fired after the cache is set on the lassoContext:
- lassoCacheCreated
- buildCacheKey
The payload of `lassoCacheCreated` actually includes `lassoContext.options`. But since options is set after the cache is set, it will always be undefined.
`buildCacheKey` also includes the lassoContext in its event payload, so this would allow `options` to also be available there.

Move setting the cache of the lassoContext to be last

---

src/LassoCache.js

Minor cleanup to the existing PR #277 which switches to leveraging promises more and prevents a potential unhandled rejection where an error was thrown synchronously in the `setImmediate` call.

Cleanup async function to prevent unhandled rejections.

---

package-lock.json
package.json
src/plugins/lasso-minify-js/index.js

Looks like previously uglify js threw errors when it couldn't minify a file, now it returns an object which was tripping us up.
This now throws the error properly from uglify js and I brought in `babel-code-frame` to make the error message a bit prettier.

Fix displaying errors when minification fails.

---

.gitignore
package-lock.json
package.json
src/require/inspect-cache.js
src/require/util/inspect.js
test/autotests/inspect/parse-error/expected.json
test/autotests/inspect/parse-error/input.js
test/inspect-test.js

Currently lasso doesn't properly display errors when it fails to parse the require's of a js file and just includes the source as is.
This change throws when the parsing fails with a formatted error.

Show formatted parse for requires.

---

src/plugins/lasso-resolve-css-urls/index.js

Lasso encountered an error while trying to resolve
`behavior: url(#default#VML);`
This is some css extensions for IE browsers. Propose to add a url resolve exception for urls beginning with a '#'.

add css resolve exception for css behavior prop

---

src/browser-refresh/index.js

The default pattern watches for `*.webp`, but `.refreshImages()` isn’t called when WEBP files change.

Include WEBP in browser-refresh imageExtensions

---

package-lock.json
package.json
src/require/util/inspect.js
test/autotests/inspect/parse-error/expected.json
test/autotests/inspect/parse-error/input.js

Switches from the (largely abandond) esprima parser to espree (maintained by the eslint team).
This allows lasso to parse some modern JS without the need for babel.

feat: switch to espree

---

src/reader.js

Ran into this recently. Fixes #71 
One alternative might be to only show the additional info if `timeout === DEFAULT_READ_TIMEOUT`.

Add bundleReadTimeout info to timeout error message
